# Generated by Django 2.2.2 on 2021-04-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20210410_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='style',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='站点样式'),
        ),
    ]
